### ISSUE TITLE
Configured Type Guid not found

### ISSUE THREAD

**Issue by FejZa** [realitycollective/com.realitycollective.service-framework#42]
Since SF v1.0.1 I get around 4 error logs in the console every time I open the SF based project:

`Configured Type Guid [77f11287-0f6d-4ac4-b709-ecefe99122ce] not found, either missing or lost to the curring room floor of Unity Code Stripping`

The errors do not cause any issues with the project and can be cleared from the console. They will appear again after relaunching the editor or entering play mode.

**Comment by FejZa** [comment]
Gotta correct myself, in one other project the issue is breaking and breaks the whole project. None of the previously working services are being registered anymore and not even being identified as services by the SF profile inspector.

**Comment by SimonDarksideJ** [comment]
Interesting, the issue itself is a fallback due to expected configuration being stripped out and not found when the project is run.
For instance, a configured service from a SubModule that was stripped by the Unity code Stripper.

Can you provide a sample project @FejZa which is exhibiting this behaviour to test with?

**Comment by SimonDarksideJ** [comment]
I've seen this come up a few times now and ALWAYS related to the entire codebase being unable to compile within Unity.  It seems to get to a point of compiling (The service framework seems first and usually works), then compilation is interrupted and stops/fails, then the Service Framework is unable to find built services because the code didn't compile and get registered with the GAC.
Not sure there is anything we can do about that, except maybe change the message.  Thoughts @FejZa ?
